[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_publish_on_not_subscribed_content_topic_works with id: 2024-12-05_12-04-57__42116b01-b4a7-48ce-b364-b8bba1768f9c
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.relay:relay.py:28 Running fixture setup: relay_setup
[35mDEBUG   [0m src.steps.sharding:sharding.py:29 Running fixture setup: sharding_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-05_12-04-57__42116b01-b4a7-48ce-b364-b8bba1768f9c__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.24.180
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['59710', '59711', '59712', '59713', '59714']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 59710:59710 -p 59711:59711 -p 59712:59712 -p 59713:59713 -p 59714:59714 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=59712 --rest-port=59710 --tcp-port=59711 --discv5-udp-port=59713 --rest-address=0.0.0.0 --nat=extip:172.18.24.180 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --nodekey=c3b11eca000e140bddafaacd8ebb8bfa810ce57e44ab3aecfcffc0f57a85de43 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=59714 --metrics-logging=true --relay=true --filter=true --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.24.180 waku 7248c1388a396a7aa84636f9e8c554496a08eab42418530f908b78906741650b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 7248c1388a39. Setting up logs at ./log/docker/node1_2024-12-05_12-04-57__42116b01-b4a7-48ce-b364-b8bba1768f9c__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 59710
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container dd60e60efce8. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:59710/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:59710/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.24.180/tcp/59711/p2p/16Uiu2HAkxVjStRNmMdKvwpSrAeQgJJ8MJ24vGbgunB3JxoxXrsCN","/ip4/172.18.24.180/tcp/59712/ws/p2p/16Uiu2HAkxVjStRNmMdKvwpSrAeQgJJ8MJ24vGbgunB3JxoxXrsCN"],"enrUri":"enr:-L24QOYiSW4IatE2mNeKB9vPqF7TTVegv_ErQe8yvE2puflNOPc_r1S5yGfVRQesMihmVWNpO_eZ9nqgVkoXnC5Wej0CgmlkgnY0gmlwhKwSGLSKbXVsdGlhZGRyc5YACASsEhi0Buk_AAoErBIYtAbpQN0DgnJzhQACAQAAiXNlY3AyNTZrMaECLZ1N58ciV2yp5KMEgOAFejwbv1dgG3V2Ly5Ez8X0eIODdGNwguk_g3VkcILpQYV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-05_12-04-57__42116b01-b4a7-48ce-b364-b8bba1768f9c__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.240.220
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['13265', '13266', '13267', '13268', '13269']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 13265:13265 -p 13266:13266 -p 13267:13267 -p 13268:13268 -p 13269:13269 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=13267 --rest-port=13265 --tcp-port=13266 --discv5-udp-port=13268 --rest-address=0.0.0.0 --nat=extip:172.18.240.220 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --nodekey=dffc30d185d7bb71e1bcbcbfdd1520f8fc4c4c5fabaed6cadd70f2a36f52dc00 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=13269 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-L24QOYiSW4IatE2mNeKB9vPqF7TTVegv_ErQe8yvE2puflNOPc_r1S5yGfVRQesMihmVWNpO_eZ9nqgVkoXnC5Wej0CgmlkgnY0gmlwhKwSGLSKbXVsdGlhZGRyc5YACASsEhi0Buk_AAoErBIYtAbpQN0DgnJzhQACAQAAiXNlY3AyNTZrMaECLZ1N58ciV2yp5KMEgOAFejwbv1dgG3V2Ly5Ez8X0eIODdGNwguk_g3VkcILpQYV3YWt1MgU --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.240.220 waku 6fbf256be2ebc5693163a2ed0675cd2268343732f8f0370f1b5caf536f538cb8
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 6fbf256be2eb. Setting up logs at ./log/docker/node2_2024-12-05_12-04-57__42116b01-b4a7-48ce-b364-b8bba1768f9c__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 13265
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:13265/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:13265/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.240.220/tcp/13266/p2p/16Uiu2HAm6NkENHLF1KgSxCihBLk2sbu55woCddbaF6ZH7YEjKTJV","/ip4/172.18.240.220/tcp/13267/ws/p2p/16Uiu2HAm6NkENHLF1KgSxCihBLk2sbu55woCddbaF6ZH7YEjKTJV"],"enrUri":"enr:-L24QFZTkEkVIvnhA440KJES6DJGLs_-u-oA_H4PWdOWk8ExQXDSgTZgdzKVcvt3K_QoADjUGcpawGq7HXNZMGchsEkCgmlkgnY0gmlwhKwS8NyKbXVsdGlhZGRyc5YACASsEvDcBjPSAAoErBLw3AYz090DgnJzhQACAQAAiXNlY3AyNTZrMaECorCe5jEJFZ4XyfvC0fWKkKTkA__7SSY2WM9wpgO5su6DdGNwgjPSg3VkcIIz1IV3YWt1MgE"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:13265/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.24.180/tcp/59711/p2p/16Uiu2HAkxVjStRNmMdKvwpSrAeQgJJ8MJ24vGbgunB3JxoxXrsCN"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:59710/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:13265/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:59710/relay/v1/auto/messages" -H "Content-Type: application/json" -d '{"payload": "U2hhcmRpbmcgd29ya3MhIQ==", "contentTopic": "/toychat/2/huilong/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:13265/relay/v1/auto/messages" -H "Content-Type: application/json" -d '{"payload": "U2hhcmRpbmcgd29ya3MhIQ==", "contentTopic": "/toychat/2/huilong/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 7248c1388a39
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 6fbf256be2eb
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 7248c1388a39. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.