[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_light_push_with_payload_around_300_kb with id: 2024-04-22_14-07-55__4b346ddc-768c-4ef6-bfb6-c75feb0fee9b
[35mDEBUG   [0m src.steps.light_push:light_push.py:27 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/receiving_node1_2024-04-22_14-07-55__4b346ddc-768c-4ef6-bfb6-c75feb0fee9b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.26.46
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['4227', '4228', '4229', '4230', '4231']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:313 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:113 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 4227:4227 -p 4228:4228 -p 4229:4229 -p 4230:4230 -p 4231:4231 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=4229 --rest-port=4227 --tcp-port=4228 --discv5-udp-port=4230 --rest-address=0.0.0.0 --nat=extip:172.18.26.46 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=4231 --metrics-logging=true --lightpush=true --relay=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.26.46 waku ca364290e6e5bcbbdde59066326b91eb231fb41c095e4b44f93a6f50b994d03b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID ca364290e6e5. Setting up logs at ./log/docker/receiving_node1_2024-04-22_14-07-55__4b346ddc-768c-4ef6-bfb6-c75feb0fee9b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:119 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 4227
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:4227/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.26.46/tcp/4228/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.26.46/tcp/4229/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QI5jZF-XsQchEJ-JtgKXg0j3muMTaeen33KGhCydRYcQT0J3OxyVQSs19VDTuUba_XawofyAhQ9DpxpM7W14BukBgmlkgnY0gmlwhKwSGi6KbXVsdGlhZGRyc4wACgSsEhouBhCF3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCEISDdWRwghCGhXdha3UyCQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:189 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/lightpush_node1_2024-04-22_14-07-55__4b346ddc-768c-4ef6-bfb6-c75feb0fee9b__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.165.77
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['22810', '22811', '22812', '22813', '22814']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:313 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:113 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 22810:22810 -p 22811:22811 -p 22812:22812 -p 22813:22813 -p 22814:22814 harbor.status.im/wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=22812 --rest-port=22810 --tcp-port=22811 --discv5-udp-port=22813 --rest-address=0.0.0.0 --nat=extip:172.18.165.77 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --discv5-bootstrap-node=enr:-LO4QI5jZF-XsQchEJ-JtgKXg0j3muMTaeen33KGhCydRYcQT0J3OxyVQSs19VDTuUba_XawofyAhQ9DpxpM7W14BukBgmlkgnY0gmlwhKwSGi6KbXVsdGlhZGRyc4wACgSsEhouBhCF3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCEISDdWRwghCGhXdha3UyCQ --lightpushnode=/ip4/172.18.26.46/tcp/4228/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip --lightpush=true --relay=false
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.165.77 waku 8e7a72861d8a83371d1796410003cc33db70a3132eee507a25eb342271dc4930
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 8e7a72861d8a. Setting up logs at ./log/docker/lightpush_node1_2024-04-22_14-07-55__4b346ddc-768c-4ef6-bfb6-c75feb0fee9b__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:119 Started container from image harbor.status.im/wakuorg/go-waku:latest. REST: 22810
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:22810/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ly4QDPu0FV_Jn8U5OjnNf5Lm38f6xADnMR2Rzkqmc00pVmhDIXq2W4HXale4-GjPxdx5qOUlcWP2bNslk_0i6hgoziGAY8GIonXgmlkgnY0gmlwhKwRAAeKbXVsdGlhZGRyc5gACgSsEQAHBlkc3QMACgR_AAABBlkc3QOJc2VjcDI1NmsxoQPdIV9Fq5eEZ7-MjDi0kT0oLx6Dd-3TYLc5jvmrKQO_dYN0Y3CCWRuDdWRwglkdhXdha3UyCA","listenAddresses":["/ip4/127.0.0.1/tcp/22811/p2p/16Uiu2HAmTYBy11noq5Aqaw3QKHsZULACwzyqhZY2mTj3FCNE4UeY","/ip4/127.0.0.1/tcp/22812/ws/p2p/16Uiu2HAmTYBy11noq5Aqaw3QKHsZULACwzyqhZY2mTj3FCNE4UeY","/ip4/172.17.0.7/tcp/22811/p2p/16Uiu2HAmTYBy11noq5Aqaw3QKHsZULACwzyqhZY2mTj3FCNE4UeY","/ip4/172.17.0.7/tcp/22812/ws/p2p/16Uiu2HAmTYBy11noq5Aqaw3QKHsZULACwzyqhZY2mTj3FCNE4UeY"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:189 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:22810/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.26.46/tcp/4228/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:4227/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m tests.light_push.test_publish:test_publish.py:61 Running test with payload length of 230400 bytes
[35mDEBUG   [0m src.steps.light_push:light_push.py:121 Lightpushing message
[32mINFO    [0m src.node.api_clients.base_client:custom_logger.py:10 Log line was discarded because it's longer than max_log_line_length=5000
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'true'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 2 seconds
[35mDEBUG   [0m src.steps.light_push:light_push.py:125 Checking that peer NODE_1:harbor.status.im/wakuorg/nwaku:latest can find the lightpushed message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:4227/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F0" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:custom_logger.py:10 Log line was discarded because it's longer than max_log_line_length=5000
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:166 Stopping container with id ca364290e6e5
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:166 Stopping container with id 8e7a72861d8a
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Container stopped.