[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_light_push_with_invalid_payloads with id: 2024-05-13_11-26-53__3c69c032-5322-41f1-a73f-7ca9a216a132
[35mDEBUG   [0m src.steps.common:common.py:15 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:27 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/receiving_node1_2024-05-13_11-26-53__3c69c032-5322-41f1-a73f-7ca9a216a132__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.6.196
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['2361', '2362', '2363', '2364', '2365']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:345 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 2361:2361 -p 2362:2362 -p 2363:2363 -p 2364:2364 -p 2365:2365 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=2363 --rest-port=2361 --tcp-port=2362 --discv5-udp-port=2364 --rest-address=0.0.0.0 --nat=extip:172.18.6.196 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=2365 --metrics-logging=true --lightpush=true --relay=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.6.196 waku 5f0d0f63172648c448db0584f020799a294e8909468fb75092cf0f5162e87048
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 5f0d0f631726. Setting up logs at ./log/docker/receiving_node1_2024-05-13_11-26-53__3c69c032-5322-41f1-a73f-7ca9a216a132__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 2361
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:2361/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:209 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:2361/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.6.196/tcp/2362/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.6.196/tcp/2363/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QFN7n3wGU1OxcBgx2wqUVL7eBzt0t2yg8BCJqQXyUHX4ctAmC72JCt8sUpn5NlsBJmOpGHHNWkjitfkq3u6m2CsBgmlkgnY0gmlwhKwSBsSKbXVsdGlhZGRyc4wACgSsEgbEBgk73QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCCTqDdWRwggk8hXdha3UyCQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:214 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/lightpush_node1_2024-05-13_11-26-53__3c69c032-5322-41f1-a73f-7ca9a216a132__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.74.99
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['29261', '29262', '29263', '29264', '29265']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:345 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 29261:29261 -p 29262:29262 -p 29263:29263 -p 29264:29264 -p 29265:29265 harbor.status.im/wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=29263 --rest-port=29261 --tcp-port=29262 --discv5-udp-port=29264 --rest-address=0.0.0.0 --nat=extip:172.18.74.99 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --discv5-bootstrap-node=enr:-LO4QFN7n3wGU1OxcBgx2wqUVL7eBzt0t2yg8BCJqQXyUHX4ctAmC72JCt8sUpn5NlsBJmOpGHHNWkjitfkq3u6m2CsBgmlkgnY0gmlwhKwSBsSKbXVsdGlhZGRyc4wACgSsEgbEBgk73QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCCTqDdWRwggk8hXdha3UyCQ --lightpushnode=/ip4/172.18.6.196/tcp/2362/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip --lightpush=true --relay=false
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.74.99 waku e66ad8c2f38b2afbca67362e8d7f6fd4d530410b95ab5b7829ea517d57a14e7e
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID e66ad8c2f38b. Setting up logs at ./log/docker/lightpush_node1_2024-05-13_11-26-53__3c69c032-5322-41f1-a73f-7ca9a216a132__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/go-waku:latest. REST: 29261
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29261/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ly4QNCa2BBXbl2436dD_y0IP7lKA6kVUEKK6SgnYy70siMjXTCp4Z2F44Vtdgk5vTisYHjgDKpilZ-6UEB-fE5G4cKGAY9xtKX5gmlkgnY0gmlwhKwRAAyKbXVsdGlhZGRyc5gACgR_AAABBnJP3QMACgSsEQAMBnJP3QOJc2VjcDI1NmsxoQKbAWilcP7W_xa7MNA4mEobo_A1Rxof0qZyW0TKZv4rXIN0Y3CCck6DdWRwgnJQhXdha3UyCA","listenAddresses":["/ip4/127.0.0.1/tcp/29262/p2p/16Uiu2HAm5rkRG3UFPnUYi1Ck7aGbTHv7QzJByjxFjuwmFVfaxsz3","/ip4/127.0.0.1/tcp/29263/ws/p2p/16Uiu2HAm5rkRG3UFPnUYi1Ck7aGbTHv7QzJByjxFjuwmFVfaxsz3","/ip4/172.17.0.12/tcp/29262/p2p/16Uiu2HAm5rkRG3UFPnUYi1Ck7aGbTHv7QzJByjxFjuwmFVfaxsz3","/ip4/172.17.0.12/tcp/29263/ws/p2p/16Uiu2HAm5rkRG3UFPnUYi1Ck7aGbTHv7QzJByjxFjuwmFVfaxsz3"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:214 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29261/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.6.196/tcp/2362/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:2361/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m tests.light_push.test_publish:test_publish.py:34 Running test with payload Empty string
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29261/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": "", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1715599616545059840}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 503 Server Error: Service Unavailable for url: http://127.0.0.1:29261/lightpush/v1/message. Response content: b'missing Payload field'
[35mDEBUG   [0m tests.light_push.test_publish:test_publish.py:34 Running test with payload Unecoded text
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29261/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": "Hello World!", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1715599616547489024}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:29261/lightpush/v1/message. Response content: b''
[35mDEBUG   [0m tests.light_push.test_publish:test_publish.py:34 Running test with payload A dictionary
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29261/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": {"key": "YWFh"}, "contentTopic": "/myapp/1/latest/proto", "timestamp": 1715599616549511936}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:29261/lightpush/v1/message. Response content: b''
[35mDEBUG   [0m tests.light_push.test_publish:test_publish.py:34 Running test with payload An integer
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29261/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": 1234567890, "contentTopic": "/myapp/1/latest/proto", "timestamp": 1715599616551780864}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:29261/lightpush/v1/message. Response content: b''
[35mDEBUG   [0m tests.light_push.test_publish:test_publish.py:34 Running test with payload A list
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29261/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": ["YWFh"], "contentTopic": "/myapp/1/latest/proto", "timestamp": 1715599616553822720}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:29261/lightpush/v1/message. Response content: b''
[35mDEBUG   [0m tests.light_push.test_publish:test_publish.py:34 Running test with payload A bool
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29261/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": true, "contentTopic": "/myapp/1/latest/proto", "timestamp": 1715599616555802880}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:29261/lightpush/v1/message. Response content: b''
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id 5f0d0f631726
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id e66ad8c2f38b
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.