[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_relay_unsubscribe_with_invalid_pubsub_topic_format with id: 2024-09-20_04-22-48__368f8ac9-7297-4974-b569-fe38e8d140a8
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.relay:relay.py:28 Running fixture setup: relay_setup
[35mDEBUG   [0m src.steps.relay:relay.py:34 Running fixture setup: setup_main_relay_nodes
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:18 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-09-20_04-22-48__368f8ac9-7297-4974-b569-fe38e8d140a8__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:21 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:24 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:81 Generated random external IP 172.18.197.42
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:74 Generated ports ['41119', '41120', '41121', '41122', '41123']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:48 docker run -i -t -p 41119:41119 -p 41120:41120 -p 41121:41121 -p 41122:41122 -p 41123:41123 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=41121 --rest-port=41119 --tcp-port=41120 --discv5-udp-port=41122 --rest-address=0.0.0.0 --nat=extip:172.18.197.42 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=ad5bbcdc9dfb9a8daabd9aa9c3dcdce8ce36b4e2fbf03dfb5d0ab8cfef0bd96a --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=41123 --metrics-logging=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 docker network connect --ip 172.18.197.42 waku 1a0b339e187140fa40c973a7e16662cc3f596e4432e68131a701d1ad6dfb295e
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:57 Container started with ID 1a0b339e1871. Setting up logs at ./log/docker/node1_2024-09-20_04-22-48__368f8ac9-7297-4974-b569-fe38e8d140a8__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/nwaku:latest. REST: 41119
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:41119/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:277 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:41119/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.197.42/tcp/41120/p2p/16Uiu2HAm6dTRvZBc3dJ5KCYCEDo5DvycJ8oCfVmRDF1zAnoNSyFx","/ip4/172.18.197.42/tcp/41121/ws/p2p/16Uiu2HAm6dTRvZBc3dJ5KCYCEDo5DvycJ8oCfVmRDF1zAnoNSyFx"],"enrUri":"enr:-LO4QNNrfZlQFfKX4LP7ed-DGHdxhyoSVkfRyJ8pWiLIkaRAZH-4KM15og9f5etLPPgdaIYd9Vkzfg0qWaRJnJ4QLMQBgmlkgnY0gmlwhKwSxSqKbXVsdGlhZGRyc4wACgSsEsUqBqCh3QOCcnOFAAMBAACJc2VjcDI1NmsxoQKmdVYO_ZHibOl6YIUjvtB8uV6hFuXimR8-WkMSw_qO-4N0Y3CCoKCDdWRwgqCihXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:18 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-09-20_04-22-48__368f8ac9-7297-4974-b569-fe38e8d140a8__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:21 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:24 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:81 Generated random external IP 172.18.238.173
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:74 Generated ports ['35439', '35440', '35441', '35442', '35443']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:434 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:163 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:165 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:48 docker run -i -t -p 35439:35439 -p 35440:35440 -p 35441:35441 -p 35442:35442 -p 35443:35443 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=35441 --rest-port=35439 --tcp-port=35440 --discv5-udp-port=35442 --rest-address=0.0.0.0 --nat=extip:172.18.238.173 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=52370d3dfad6bfe70ebbaab410a2bfceff82cf946b65bcd2647a81e8472b9fea --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=35443 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-LO4QNNrfZlQFfKX4LP7ed-DGHdxhyoSVkfRyJ8pWiLIkaRAZH-4KM15og9f5etLPPgdaIYd9Vkzfg0qWaRJnJ4QLMQBgmlkgnY0gmlwhKwSxSqKbXVsdGlhZGRyc4wACgSsEsUqBqCh3QOCcnOFAAMBAACJc2VjcDI1NmsxoQKmdVYO_ZHibOl6YIUjvtB8uV6hFuXimR8-WkMSw_qO-4N0Y3CCoKCDdWRwgqCihXdha3UyAQ
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 docker network connect --ip 172.18.238.173 waku ca010dd6aec61a2a7198edd13d3d6c32efb4e3f4057d6ab9bcd5a16d805b528e
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:57 Container started with ID ca010dd6aec6. Setting up logs at ./log/docker/node2_2024-09-20_04-22-48__368f8ac9-7297-4974-b569-fe38e8d140a8__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:177 Started container from image wakuorg/nwaku:latest. REST: 35439
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:35439/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:277 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:35439/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.238.173/tcp/35440/p2p/16Uiu2HAmG4kaBtSTVBYTc8gYU7bcov5M1BzRXrX9aJgfmdMWzFd5","/ip4/172.18.238.173/tcp/35441/ws/p2p/16Uiu2HAmG4kaBtSTVBYTc8gYU7bcov5M1BzRXrX9aJgfmdMWzFd5"],"enrUri":"enr:-LO4QCUBymB5ElQPUCWT-Pi5Zp_g7dmWfzQZZ7IqR16dlKRKAoeKBMQ2CnYwpx5YL7xFzDDW2_n_kE6PHdVJ7t9_fmIBgmlkgnY0gmlwhKwS7q2KbXVsdGlhZGRyc4wACgSsEu6tBopx3QOCcnOFAAMBAACJc2VjcDI1NmsxoQMyqWv7WcR7iORDW_oee1xnbTTBjgxt8fsjXDSCwen1XIN0Y3CCinCDdWRwgopyhXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:35439/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.197.42/tcp/41120/p2p/16Uiu2HAm6dTRvZBc3dJ5KCYCEDo5DvycJ8oCfVmRDF1zAnoNSyFx"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m tests.relay.test_subscribe:test_subscribe.py:88 Running test with payload /test/2/rs/0/1
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X DELETE "http://127.0.0.1:41119/relay/v1/subscriptions" -H "Content-Type: application/json" -d '"/test/2/rs/0/1"'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:41119/relay/v1/subscriptions. Response content: b'Invalid content body, could not decode. Unable to deserialize data'
[35mDEBUG   [0m tests.relay.test_subscribe:test_subscribe.py:88 Running test with payload /waku/3/rs/0/1
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X DELETE "http://127.0.0.1:41119/relay/v1/subscriptions" -H "Content-Type: application/json" -d '"/waku/3/rs/0/1"'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:41119/relay/v1/subscriptions. Response content: b'Invalid content body, could not decode. Unable to deserialize data'
[35mDEBUG   [0m tests.relay.test_subscribe:test_subscribe.py:88 Running test with payload /waku/2/test/0/1
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X DELETE "http://127.0.0.1:41119/relay/v1/subscriptions" -H "Content-Type: application/json" -d '"/waku/2/test/0/1"'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:41119/relay/v1/subscriptions. Response content: b'Invalid content body, could not decode. Unable to deserialize data'
[35mDEBUG   [0m tests.relay.test_subscribe:test_subscribe.py:88 Running test with payload /waku/2/rs/3/b
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X DELETE "http://127.0.0.1:41119/relay/v1/subscriptions" -H "Content-Type: application/json" -d '"/waku/2/rs/3/b"'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:41119/relay/v1/subscriptions. Response content: b'Invalid content body, could not decode. Unable to deserialize data'
[35mDEBUG   [0m tests.relay.test_subscribe:test_subscribe.py:88 Running test with payload /waku/2/rs/0
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X DELETE "http://127.0.0.1:41119/relay/v1/subscriptions" -H "Content-Type: application/json" -d '"/waku/2/rs/0"'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:41119/relay/v1/subscriptions. Response content: b'Invalid content body, could not decode. Unable to deserialize data'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id 1a0b339e1871
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:221 Stopping container with id ca010dd6aec6
[35mDEBUG   [0m src.node.waku_node:waku_node.py:228 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:117 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:117 No errors found in the waku logs.