[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_filter_unsubscribe_with_no_request_id with id: 2024-03-03_04-12-43__edc88cef-f356-437f-bc39-fc5ff0efcef0
[35mDEBUG   [0m src.steps.filter:filter.py:27 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:33 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node1_2024-03-03_04-12-43__edc88cef-f356-437f-bc39-fc5ff0efcef0__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:78 Generated random external IP 172.18.173.181
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:71 Generated ports ['11018', '11019', '11020', '11021', '11022']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:276 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:45 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:46 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=11020', '--rest-port=11018', '--tcp-port=11019', '--discv5-udp-port=11021', '--rest-address=0.0.0.0', '--nat=extip:172.18.173.181', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=11022', '--metrics-logging=true', '--relay=true', '--filter=true', '--nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 Container started with ID 8f1d1a96dddc. Setting up logs at ./log/docker/node1_2024-03-03_04-12-43__edc88cef-f356-437f-bc39-fc5ff0efcef0__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 11018
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:11018/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.173.181/tcp/11019/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.173.181/tcp/11020/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-Kq4QFm1MfcAgWv9P6OBwghkz1NnXFElmwwxgURBkWL_jhZoDWG0V0j2FMC_ieejN-W8cH2DhdqXxYSKTiD6vINoZQUBgmlkgnY0gmlwhKwSrbWKbXVsdGlhZGRyc4wACgSsEq21BisM3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCKwuDdWRwgisNhXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:38 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node2_2024-03-03_04-12-43__edc88cef-f356-437f-bc39-fc5ff0efcef0__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:78 Generated random external IP 172.18.155.168
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:71 Generated ports ['24096', '24097', '24098', '24099', '24100']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:276 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:45 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:46 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=24098', '--rest-port=24096', '--tcp-port=24097', '--discv5-udp-port=24099', '--rest-address=0.0.0.0', '--nat=extip:172.18.155.168', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=24100', '--metrics-logging=true', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QFm1MfcAgWv9P6OBwghkz1NnXFElmwwxgURBkWL_jhZoDWG0V0j2FMC_ieejN-W8cH2DhdqXxYSKTiD6vINoZQUBgmlkgnY0gmlwhKwSrbWKbXVsdGlhZGRyc4wACgSsEq21BisM3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCKwuDdWRwgisNhXdha3UyBQ', '--filternode=/ip4/172.18.173.181/tcp/11019/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 Container started with ID 9e3a5da2288f. Setting up logs at ./log/docker/node2_2024-03-03_04-12-43__edc88cef-f356-437f-bc39-fc5ff0efcef0__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 24096
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:24096/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.155.168/tcp/24097/p2p/16Uiu2HAmR7ZcdUzeVwrokSep8Tg9kYkXbDXNjB9wo3gPMpZm9KiL","/ip4/172.18.155.168/tcp/24098/ws/p2p/16Uiu2HAmR7ZcdUzeVwrokSep8Tg9kYkXbDXNjB9wo3gPMpZm9KiL"],"enrUri":"enr:-Kq4QFM19z6y0FkT-MBzUXorzCe70c77vmsjX3nLIgbYvUMpHv-OgaQezmHF6cfZlpPSj_BIHKX7zab9fpBEeZpMnkIBgmlkgnY0gmlwhKwSm6iKbXVsdGlhZGRyc4wACgSsEpuoBl4i3QOJc2VjcDI1NmsxoQO5GvTYDycJMZhtTU63bwbXFmg5vWzjGMJ3Yxs1Zj9VpYN0Y3CCXiGDdWRwgl4jhXdha3UyBA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:45 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 POST call: http://127.0.0.1:11018/relay/v1/subscriptions with payload: ["/waku/2/rs/0/1"]
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 POST call: http://127.0.0.1:24096/filter/v2/subscriptions with payload: {"requestId": "1899e628-1616-4e77-a81d-70145378ded4", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"1899e628-1616-4e77-a81d-70145378ded4","statusCode":0,"statusDesc":""}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 DELETE call: http://127.0.0.1:24096/filter/v2/subscriptions with payload: {"contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:24096/filter/v2/subscriptions. Response content: b'{"requestId":"unknown","statusCode":400,"statusDesc":"BAD_REQUEST: Failed to decode request: (status: 400 Bad Request, headers: , kind: Error, errobj: (status: 400 Bad Request, message: \\"Invalid content body, could not decode. Unable to deserialize data\\", contentType: \\"text/plain\\"))"}'
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 8f1d1a96dddc
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 9e3a5da2288f
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.