[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_ping_only_some_nodes_have_subscriptions with id: 2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.56.60
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['28472', '28473', '28474', '28475', '28476']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 28472:28472 -p 28473:28473 -p 28474:28474 -p 28475:28475 -p 28476:28476 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=28474 --rest-port=28472 --tcp-port=28473 --discv5-udp-port=28475 --rest-address=0.0.0.0 --nat=extip:172.18.56.60 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=31ee1fdd66dbc71cd849dccd4c1de367f7ac9faa310faaf47da5acff6b55bf10 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=28476 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.56.60 waku 93ab7a4ccedab108f448b1175d7af1e9718fc1c062548fb1be8104cd1420c26c
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 93ab7a4cceda. Setting up logs at ./log/docker/node1_2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 28472
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container edea3805b146. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:28472/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:28472/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.56.60/tcp/28473/p2p/16Uiu2HAmS7cCXFYN4w85WR2HCEe7kMmTqnXseSTDiZtKwo7UqFHR","/ip4/172.18.56.60/tcp/28474/ws/p2p/16Uiu2HAmS7cCXFYN4w85WR2HCEe7kMmTqnXseSTDiZtKwo7UqFHR"],"enrUri":"enr:-L24QJtnsZKuc9X2w82UvL62UFlZlYYHY0ja5vvKMYcBJR2LKs2jHRWKCyJuVx6AbxMCHzOqEVC0gl1cbkn5K3snPFoCgmlkgnY0gmlwhKwSODyKbXVsdGlhZGRyc5YACASsEjg8Bm85AAoErBI4PAZvOt0DgnJzhQADAQAAiXNlY3AyNTZrMaEDx_mQw8CD78Xt-fd6YR-BsaV6qJBKaP5fiCh4OjgPRCCDdGNwgm85g3VkcIJvO4V3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.9.230
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['48976', '48977', '48978', '48979', '48980']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 48976:48976 -p 48977:48977 -p 48978:48978 -p 48979:48979 -p 48980:48980 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=48978 --rest-port=48976 --tcp-port=48977 --discv5-udp-port=48979 --rest-address=0.0.0.0 --nat=extip:172.18.9.230 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=aa77fe7fed72c2bd60baaa6560dbadcdbbaab0ed478f4322becdca4b1c247bd9 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=48980 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QJtnsZKuc9X2w82UvL62UFlZlYYHY0ja5vvKMYcBJR2LKs2jHRWKCyJuVx6AbxMCHzOqEVC0gl1cbkn5K3snPFoCgmlkgnY0gmlwhKwSODyKbXVsdGlhZGRyc5YACASsEjg8Bm85AAoErBI4PAZvOt0DgnJzhQADAQAAiXNlY3AyNTZrMaEDx_mQw8CD78Xt-fd6YR-BsaV6qJBKaP5fiCh4OjgPRCCDdGNwgm85g3VkcIJvO4V3YWt1MgU --filternode=/ip4/172.18.56.60/tcp/28473/p2p/16Uiu2HAmS7cCXFYN4w85WR2HCEe7kMmTqnXseSTDiZtKwo7UqFHR
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.9.230 waku e48af90a5bf4639f1e38a79ff96c4f83e9396554ca7476e7305e56aefb7b37f3
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID e48af90a5bf4. Setting up logs at ./log/docker/node2_2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 48976
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:48976/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:48976/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.9.230/tcp/48977/p2p/16Uiu2HAm9V7sSnxB22GD9c8dVNwpCkA7wgGws6zSwZ1sqALYfpFs","/ip4/172.18.9.230/tcp/48978/ws/p2p/16Uiu2HAm9V7sSnxB22GD9c8dVNwpCkA7wgGws6zSwZ1sqALYfpFs"],"enrUri":"enr:-L24QBi4OImL2YxKJlsaw-c21et_z5mVz-mfXoI9S4GVgAJlPAXA3wLZo3XU8ZaxvjR0GfV_wQ1lGpeEukpppxewae8CgmlkgnY0gmlwhKwSCeaKbXVsdGlhZGRyc5YACASsEgnmBr9RAAoErBIJ5ga_Ut0DgnJzhQADAQAAiXNlY3AyNTZrMaEC0OWiSaR-FjKE--EY07tHsNBXJQath3muuYa5yAR8oPqDdGNwgr9Rg3VkcIK_U4V3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:48976/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.56.60/tcp/28473/p2p/16Uiu2HAmS7cCXFYN4w85WR2HCEe7kMmTqnXseSTDiZtKwo7UqFHR"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:28472/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:48976/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "dd3a3262-f39f-4647-bb01-cefd23d1d887", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"dd3a3262-f39f-4647-bb01-cefd23d1d887","statusDesc":"OK"}'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node3_2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.224.94
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['58258', '58259', '58260', '58261', '58262']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 58258:58258 -p 58259:58259 -p 58260:58260 -p 58261:58261 -p 58262:58262 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=58260 --rest-port=58258 --tcp-port=58259 --discv5-udp-port=58261 --rest-address=0.0.0.0 --nat=extip:172.18.224.94 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=91faf9eedffd71dbff55f7b5e1dca17ef101ebfe9b449f55c5fdd67ca3ba7cde --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=58262 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QJtnsZKuc9X2w82UvL62UFlZlYYHY0ja5vvKMYcBJR2LKs2jHRWKCyJuVx6AbxMCHzOqEVC0gl1cbkn5K3snPFoCgmlkgnY0gmlwhKwSODyKbXVsdGlhZGRyc5YACASsEjg8Bm85AAoErBI4PAZvOt0DgnJzhQADAQAAiXNlY3AyNTZrMaEDx_mQw8CD78Xt-fd6YR-BsaV6qJBKaP5fiCh4OjgPRCCDdGNwgm85g3VkcIJvO4V3YWt1MgU --filternode=/ip4/172.18.56.60/tcp/28473/p2p/16Uiu2HAmS7cCXFYN4w85WR2HCEe7kMmTqnXseSTDiZtKwo7UqFHR
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.224.94 waku 561ad1b46fd689546944999ba23ce8cf0153a1e45e399321707653ff96774a42
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 561ad1b46fd6. Setting up logs at ./log/docker/node3_2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 58258
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58258/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58258/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.224.94/tcp/58259/p2p/16Uiu2HAm9Pyx7yVzcswrH3aWNRfrJydpeMz4mNuLoquQA5Sx7QxT","/ip4/172.18.224.94/tcp/58260/ws/p2p/16Uiu2HAm9Pyx7yVzcswrH3aWNRfrJydpeMz4mNuLoquQA5Sx7QxT"],"enrUri":"enr:-L24QITsq6sXzzD4zV8nRdOAFEdJwMIKMumBY6aLNnI9aG4nAOtREC1GvEFSomok_4tHDAw5m_hiBaIGBhAEtz53Ss0CgmlkgnY0gmlwhKwS4F6KbXVsdGlhZGRyc5YACASsEuBeBuOTAAoErBLgXgbjlN0DgnJzhQADAQAAiXNlY3AyNTZrMaECz5TGgVr2hzeEEygS999UzB2Da7m1nZuCa2q08eA1OUyDdGNwguOTg3VkcILjlYV3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:58258/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.56.60/tcp/28473/p2p/16Uiu2HAmS7cCXFYN4w85WR2HCEe7kMmTqnXseSTDiZtKwo7UqFHR"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node4_2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.245.59
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['49239', '49240', '49241', '49242', '49243']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 49239:49239 -p 49240:49240 -p 49241:49241 -p 49242:49242 -p 49243:49243 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=49241 --rest-port=49239 --tcp-port=49240 --discv5-udp-port=49242 --rest-address=0.0.0.0 --nat=extip:172.18.245.59 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=fcacbbdf7a4f066a370efafa778e96b6c40f20244b4ab4c11bba2e5be061fac6 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=49243 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QJtnsZKuc9X2w82UvL62UFlZlYYHY0ja5vvKMYcBJR2LKs2jHRWKCyJuVx6AbxMCHzOqEVC0gl1cbkn5K3snPFoCgmlkgnY0gmlwhKwSODyKbXVsdGlhZGRyc5YACASsEjg8Bm85AAoErBI4PAZvOt0DgnJzhQADAQAAiXNlY3AyNTZrMaEDx_mQw8CD78Xt-fd6YR-BsaV6qJBKaP5fiCh4OjgPRCCDdGNwgm85g3VkcIJvO4V3YWt1MgU --filternode=/ip4/172.18.56.60/tcp/28473/p2p/16Uiu2HAmS7cCXFYN4w85WR2HCEe7kMmTqnXseSTDiZtKwo7UqFHR
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.245.59 waku c6ce3bb4687380ff553fd620d17dfcd24b927b616907fa4238e557fa8894ad06
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID c6ce3bb46873. Setting up logs at ./log/docker/node4_2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 49239
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:49239/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:49239/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.245.59/tcp/49240/p2p/16Uiu2HAmU2jfi6DNqEEmCpZfsEyZV6fciZgVRbk4rZxRRUQ692A3","/ip4/172.18.245.59/tcp/49241/ws/p2p/16Uiu2HAmU2jfi6DNqEEmCpZfsEyZV6fciZgVRbk4rZxRRUQ692A3"],"enrUri":"enr:-L24QAgkCPXbkXZjta_HtWq2Y_b9_YmSywlhAMUHCvfpShjLP0tNmh7uIDZoVH7v7CYuMFy-T2bqTHxPCxb2Akup598CgmlkgnY0gmlwhKwS9TuKbXVsdGlhZGRyc5YACASsEvU7BsBYAAoErBL1OwbAWd0DgnJzhQADAQAAiXNlY3AyNTZrMaED5HF68ALSOZ9VjJ1D8rOUWtgWBfFf9mksf2OWwUA1HeCDdGNwgsBYg3VkcILAWoV3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:49239/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.56.60/tcp/28473/p2p/16Uiu2HAmS7cCXFYN4w85WR2HCEe7kMmTqnXseSTDiZtKwo7UqFHR"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node5_2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.241.2
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['11306', '11307', '11308', '11309', '11310']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 11306:11306 -p 11307:11307 -p 11308:11308 -p 11309:11309 -p 11310:11310 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=11308 --rest-port=11306 --tcp-port=11307 --discv5-udp-port=11309 --rest-address=0.0.0.0 --nat=extip:172.18.241.2 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=d40ef96841b5da7be63100338b0ac876dfc57bcbf5df8bbd0bb553d002b6b3d0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=11310 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QJtnsZKuc9X2w82UvL62UFlZlYYHY0ja5vvKMYcBJR2LKs2jHRWKCyJuVx6AbxMCHzOqEVC0gl1cbkn5K3snPFoCgmlkgnY0gmlwhKwSODyKbXVsdGlhZGRyc5YACASsEjg8Bm85AAoErBI4PAZvOt0DgnJzhQADAQAAiXNlY3AyNTZrMaEDx_mQw8CD78Xt-fd6YR-BsaV6qJBKaP5fiCh4OjgPRCCDdGNwgm85g3VkcIJvO4V3YWt1MgU --filternode=/ip4/172.18.56.60/tcp/28473/p2p/16Uiu2HAmS7cCXFYN4w85WR2HCEe7kMmTqnXseSTDiZtKwo7UqFHR
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.241.2 waku 95859f2d0e6f8c5944af71dd0c5266eb6b19502ce2b67f60b62811cff24a7263
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 95859f2d0e6f. Setting up logs at ./log/docker/node5_2025-01-05_04-10-08__dd8824ec-b76d-473b-bfae-12cd6dca4f59__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 11306
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:11306/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:11306/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.241.2/tcp/11307/p2p/16Uiu2HAm6KDkVrRqnzya7NLag4utYHkcoCnKFXGTZriXR4ARM6bd","/ip4/172.18.241.2/tcp/11308/ws/p2p/16Uiu2HAm6KDkVrRqnzya7NLag4utYHkcoCnKFXGTZriXR4ARM6bd"],"enrUri":"enr:-L24QE9iRJGjytEeEoiOui5aPR63DIG7DAtBXfgIb7TQ8VN2OO-2mItshKdwsC3BnT_31kXpBTamUfzpC1zmPhgwQ0oCgmlkgnY0gmlwhKwS8QKKbXVsdGlhZGRyc5YACASsEvECBiwrAAoErBLxAgYsLN0DgnJzhQADAQAAiXNlY3AyNTZrMaECoclp8jlZbE_JI7d-xlEGmeW0SSs0V5IcKav5YPU7q4yDdGNwgiwrg3VkcIIsLYV3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:11306/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.56.60/tcp/28473/p2p/16Uiu2HAmS7cCXFYN4w85WR2HCEe7kMmTqnXseSTDiZtKwo7UqFHR"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:48976/filter/v2/subscriptions/1" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"1","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58258/filter/v2/subscriptions/23baab8b-ef9d-4b30-ad0a-a6e0320c95ad" -H "Content-Type: application/json" -d 'None'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 404 Client Error: Not Found for url: http://127.0.0.1:58258/filter/v2/subscriptions/23baab8b-ef9d-4b30-ad0a-a6e0320c95ad. Response content: b'{"requestId":"23baab8b-ef9d-4b30-ad0a-a6e0320c95ad","statusDesc":"NOT_FOUND: peer has no subscriptions"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:49239/filter/v2/subscriptions/bfffacd7-0fcc-44bc-a10b-5a859a136926" -H "Content-Type: application/json" -d 'None'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 404 Client Error: Not Found for url: http://127.0.0.1:49239/filter/v2/subscriptions/bfffacd7-0fcc-44bc-a10b-5a859a136926. Response content: b'{"requestId":"bfffacd7-0fcc-44bc-a10b-5a859a136926","statusDesc":"NOT_FOUND: peer has no subscriptions"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:11306/filter/v2/subscriptions/1a6f6899-a580-400e-877b-cc11d2890fac" -H "Content-Type: application/json" -d 'None'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 404 Client Error: Not Found for url: http://127.0.0.1:11306/filter/v2/subscriptions/1a6f6899-a580-400e-877b-cc11d2890fac. Response content: b'{"requestId":"1a6f6899-a580-400e-877b-cc11d2890fac","statusDesc":"NOT_FOUND: peer has no subscriptions"}'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 93ab7a4cceda
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id e48af90a5bf4
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 93ab7a4cceda. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 561ad1b46fd6
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container e48af90a5bf4. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id c6ce3bb46873
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 561ad1b46fd6. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 95859f2d0e6f
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container c6ce3bb46873. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.