[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_light_push_while_peer_is_paused with id: 2024-05-24_10-01-13__6969e08d-100f-47ff-820b-7bbc8bff3531
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:27 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/receiving_node1_2024-05-24_10-01-13__6969e08d-100f-47ff-820b-7bbc8bff3531__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.198.254
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['27767', '27768', '27769', '27770', '27771']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:357 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 27767:27767 -p 27768:27768 -p 27769:27769 -p 27770:27770 -p 27771:27771 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=27769 --rest-port=27767 --tcp-port=27768 --discv5-udp-port=27770 --rest-address=0.0.0.0 --nat=extip:172.18.198.254 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=27771 --metrics-logging=true --lightpush=true --relay=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.198.254 waku 0758a813029afb9d622b9e6ede72a3cefb03034c8f65dd83d5eba4c166f11982
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 0758a813029a. Setting up logs at ./log/docker/receiving_node1_2024-05-24_10-01-13__6969e08d-100f-47ff-820b-7bbc8bff3531__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 27767
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:27767/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:209 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:27767/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.198.254/tcp/27768/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.198.254/tcp/27769/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QMGqiRgl9OuVc8jNeXdhPWv3b9_KVVj9fXS6ps3JyrQyEL8kp3V896OoyrGeqYkjDmPIGZxAl8KM9fcKjg4B7WABgmlkgnY0gmlwhKwSxv6KbXVsdGlhZGRyc4wACgSsEsb-Bmx53QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCbHiDdWRwgmx6hXdha3UyCQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:214 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/lightpush_node1_2024-05-24_10-01-13__6969e08d-100f-47ff-820b-7bbc8bff3531__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.80.206
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['10819', '10820', '10821', '10822', '10823']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:357 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 10819:10819 -p 10820:10820 -p 10821:10821 -p 10822:10822 -p 10823:10823 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=10821 --rest-port=10819 --tcp-port=10820 --discv5-udp-port=10822 --rest-address=0.0.0.0 --nat=extip:172.18.80.206 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=10823 --metrics-logging=true --discv5-bootstrap-node=enr:-LO4QMGqiRgl9OuVc8jNeXdhPWv3b9_KVVj9fXS6ps3JyrQyEL8kp3V896OoyrGeqYkjDmPIGZxAl8KM9fcKjg4B7WABgmlkgnY0gmlwhKwSxv6KbXVsdGlhZGRyc4wACgSsEsb-Bmx53QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCbHiDdWRwgmx6hXdha3UyCQ --lightpushnode=/ip4/172.18.198.254/tcp/27768/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip --lightpush=true --relay=false
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.80.206 waku e1c191a927d9cbfae34b396de49ec193f1ac6bb501ecf38ab7ecf0c579fd4992
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID e1c191a927d9. Setting up logs at ./log/docker/lightpush_node1_2024-05-24_10-01-13__6969e08d-100f-47ff-820b-7bbc8bff3531__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 10819
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:10819/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:209 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:10819/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.80.206/tcp/10820/p2p/16Uiu2HAm8QWDeBRZ3jwUFSp7jjWLHDBJNsfxuqBuKQ9tBgGyCahJ","/ip4/172.18.80.206/tcp/10821/ws/p2p/16Uiu2HAm8QWDeBRZ3jwUFSp7jjWLHDBJNsfxuqBuKQ9tBgGyCahJ"],"enrUri":"enr:-LO4QClD28wRHJKOQYy7NdQxDrfKO_yNF5db8aLHQ71cXHtEX8meW12TK4wy8dKwBqs9r-sqSyLLRf8qJaby1vyQ7qQBgmlkgnY0gmlwhKwSUM6KbXVsdGlhZGRyc4wACgSsElDOBipF3QOCcnOFAAABAACJc2VjcDI1NmsxoQLA20_qUHmEW4HJZbzcAtvcaPUGMa1wx_8OtBb1reHmHYN0Y3CCKkSDdWRwgipGhXdha3UyCA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:214 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:10819/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.198.254/tcp/27768/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:27767/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id 0758a813029a
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:10819/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": "TGlnaHQgcHVzaCB3b3JrcyEh", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1716544876966629888}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 503 Server Error: Service Unavailable for url: http://127.0.0.1:10819/lightpush/v1/message. Response content: b'Failed to request a message push: dial_failure'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id e1c191a927d9
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:73 Running fixture teardown: attach_logs_on_fail
[35mDEBUG   [0m tests.conftest:conftest.py:74 Test failed, attempting to attach logs to the allure reports
[35mDEBUG   [0m src.libs.common:common.py:30 Attaching file ./log/docker/receiving_node1_2024-05-24_10-01-13__6969e08d-100f-47ff-820b-7bbc8bff3531__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.libs.common:common.py:30 Attaching file ./log/docker/lightpush_node1_2024-05-24_10-01-13__6969e08d-100f-47ff-820b-7bbc8bff3531__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_light_push_while_peer_is_paused with id: 2024-05-24_10-01-26__2080031b-5532-4d34-82ff-0d568d224e35
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:27 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/receiving_node1_2024-05-24_10-01-26__2080031b-5532-4d34-82ff-0d568d224e35__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.237.57
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['54203', '54204', '54205', '54206', '54207']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:357 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 54203:54203 -p 54204:54204 -p 54205:54205 -p 54206:54206 -p 54207:54207 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=54205 --rest-port=54203 --tcp-port=54204 --discv5-udp-port=54206 --rest-address=0.0.0.0 --nat=extip:172.18.237.57 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=54207 --metrics-logging=true --lightpush=true --relay=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.237.57 waku 4f00fa36d6382bd16bb170ff2f63bc51857874bfd7fa51a35d1b2dc54be59e75
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 4f00fa36d638. Setting up logs at ./log/docker/receiving_node1_2024-05-24_10-01-26__2080031b-5532-4d34-82ff-0d568d224e35__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 54203
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:54203/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:209 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:54203/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.237.57/tcp/54204/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.237.57/tcp/54205/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QOO72Z_rjUMCRyOF3XU_WAMxitRvZb5GAfCUCd5LtNVfXKmaOlNCTFMIfrhMruPkTEiqrHPAb4Uv_cMC3ftB6BEBgmlkgnY0gmlwhKwS7TmKbXVsdGlhZGRyc4wACgSsEu05BtO93QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC07yDdWRwgtO-hXdha3UyCQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:214 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/lightpush_node1_2024-05-24_10-01-26__2080031b-5532-4d34-82ff-0d568d224e35__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.108.162
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['37039', '37040', '37041', '37042', '37043']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:357 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 37039:37039 -p 37040:37040 -p 37041:37041 -p 37042:37042 -p 37043:37043 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=37041 --rest-port=37039 --tcp-port=37040 --discv5-udp-port=37042 --rest-address=0.0.0.0 --nat=extip:172.18.108.162 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=37043 --metrics-logging=true --discv5-bootstrap-node=enr:-LO4QOO72Z_rjUMCRyOF3XU_WAMxitRvZb5GAfCUCd5LtNVfXKmaOlNCTFMIfrhMruPkTEiqrHPAb4Uv_cMC3ftB6BEBgmlkgnY0gmlwhKwS7TmKbXVsdGlhZGRyc4wACgSsEu05BtO93QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC07yDdWRwgtO-hXdha3UyCQ --lightpushnode=/ip4/172.18.237.57/tcp/54204/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip --lightpush=true --relay=false
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.108.162 waku afea78326178b0a7c01e8826648d6c0ee6a3d55896b82a9a15d409a26cacd33b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID afea78326178. Setting up logs at ./log/docker/lightpush_node1_2024-05-24_10-01-26__2080031b-5532-4d34-82ff-0d568d224e35__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 37039
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:37039/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:209 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:37039/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.108.162/tcp/37040/p2p/16Uiu2HAmRZc5rn8B3CTnopKruiYt4yqHwVGyhxn2u9vbYjdgj85N","/ip4/172.18.108.162/tcp/37041/ws/p2p/16Uiu2HAmRZc5rn8B3CTnopKruiYt4yqHwVGyhxn2u9vbYjdgj85N"],"enrUri":"enr:-LO4QGGVKYgMcm07ZhSvxOZ0FVj-59x7DQkQr1b5Yb4_NiXdeEclYTboVyUzTvcyToe-qvDiEzr1X2oWIxy2KazB-cABgmlkgnY0gmlwhKwSbKKKbXVsdGlhZGRyc4wACgSsEmyiBpCx3QOCcnOFAAABAACJc2VjcDI1NmsxoQO_xtmFqfPL_8SBN88zkMxSZ6eBd_u_CkKv5vh9skgPeYN0Y3CCkLCDdWRwgpCyhXdha3UyCA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:214 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:37039/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.237.57/tcp/54204/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:54203/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id 4f00fa36d638
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:37039/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": "TGlnaHQgcHVzaCB3b3JrcyEh", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1716544890351063552}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 503 Server Error: Service Unavailable for url: http://127.0.0.1:37039/lightpush/v1/message. Response content: b'Failed to request a message push: dial_failure'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id afea78326178
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:73 Running fixture teardown: attach_logs_on_fail
[35mDEBUG   [0m tests.conftest:conftest.py:74 Test failed, attempting to attach logs to the allure reports
[35mDEBUG   [0m src.libs.common:common.py:30 Attaching file ./log/docker/receiving_node1_2024-05-24_10-01-26__2080031b-5532-4d34-82ff-0d568d224e35__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.libs.common:common.py:30 Attaching file ./log/docker/lightpush_node1_2024-05-24_10-01-26__2080031b-5532-4d34-82ff-0d568d224e35__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_light_push_while_peer_is_paused with id: 2024-05-24_10-01-39__7cdfc000-5693-4254-96b1-accc9b124ac6
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:27 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/receiving_node1_2024-05-24_10-01-39__7cdfc000-5693-4254-96b1-accc9b124ac6__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.211.111
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['33644', '33645', '33646', '33647', '33648']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:357 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 33644:33644 -p 33645:33645 -p 33646:33646 -p 33647:33647 -p 33648:33648 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=33646 --rest-port=33644 --tcp-port=33645 --discv5-udp-port=33647 --rest-address=0.0.0.0 --nat=extip:172.18.211.111 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=33648 --metrics-logging=true --lightpush=true --relay=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.211.111 waku 45042a27aa0cc52ec33146561a7abe3c97cb72c25364b87f1f79395072a3d247
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 45042a27aa0c. Setting up logs at ./log/docker/receiving_node1_2024-05-24_10-01-39__7cdfc000-5693-4254-96b1-accc9b124ac6__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 33644
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:33644/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:209 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:33644/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.211.111/tcp/33645/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.211.111/tcp/33646/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QNlw3ptU2r3OXRb9Vbl_zVCLiEvgJgs7u5UaqOrz5ElmHLvLY0FIR6TTr8AL8zLN3_vp3UmXQ_1YCiX9hjNoso0BgmlkgnY0gmlwhKwS02-KbXVsdGlhZGRyc4wACgSsEtNvBoNu3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCg22DdWRwgoNvhXdha3UyCQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:214 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/lightpush_node1_2024-05-24_10-01-39__7cdfc000-5693-4254-96b1-accc9b124ac6__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.152.94
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['52652', '52653', '52654', '52655', '52656']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:357 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 52652:52652 -p 52653:52653 -p 52654:52654 -p 52655:52655 -p 52656:52656 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=52654 --rest-port=52652 --tcp-port=52653 --discv5-udp-port=52655 --rest-address=0.0.0.0 --nat=extip:172.18.152.94 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=52656 --metrics-logging=true --discv5-bootstrap-node=enr:-LO4QNlw3ptU2r3OXRb9Vbl_zVCLiEvgJgs7u5UaqOrz5ElmHLvLY0FIR6TTr8AL8zLN3_vp3UmXQ_1YCiX9hjNoso0BgmlkgnY0gmlwhKwS02-KbXVsdGlhZGRyc4wACgSsEtNvBoNu3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCg22DdWRwgoNvhXdha3UyCQ --lightpushnode=/ip4/172.18.211.111/tcp/33645/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip --lightpush=true --relay=false
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.152.94 waku 89d38ef9f1515be8f182a2f41d8ef2718b83165d8d460d035969c6f9b8783805
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 89d38ef9f151. Setting up logs at ./log/docker/lightpush_node1_2024-05-24_10-01-39__7cdfc000-5693-4254-96b1-accc9b124ac6__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 52652
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:52652/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:209 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:52652/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.152.94/tcp/52653/p2p/16Uiu2HAmECbbiRhkatSfGKo2XmLMNMKsTRvZiHz8BLidKcqrssnq","/ip4/172.18.152.94/tcp/52654/ws/p2p/16Uiu2HAmECbbiRhkatSfGKo2XmLMNMKsTRvZiHz8BLidKcqrssnq"],"enrUri":"enr:-LO4QHzjj2gtR9K38fQ3_KMzHOiA6tz3TE4bXnNu7LhCAkroctVPmBRqOCz_UHOr9K7zD7JgcBiKUsHRtt33yNtoS8oBgmlkgnY0gmlwhKwSmF6KbXVsdGlhZGRyc4wACgSsEpheBs2u3QOCcnOFAAABAACJc2VjcDI1NmsxoQMW9Iw_-OzVbwaWo5WJTlDLGgzORp4xtZGJIVlgOidXCoN0Y3CCza2DdWRwgs2vhXdha3UyCA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:214 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:52652/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.211.111/tcp/33645/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:33644/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id 45042a27aa0c
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:52652/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": "TGlnaHQgcHVzaCB3b3JrcyEh", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1716544903035559936}}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 503 Server Error: Service Unavailable for url: http://127.0.0.1:52652/lightpush/v1/message. Response content: b'Failed to request a message push: dial_failure'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id 89d38ef9f151
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:73 Running fixture teardown: attach_logs_on_fail
[35mDEBUG   [0m tests.conftest:conftest.py:74 Test failed, attempting to attach logs to the allure reports
[35mDEBUG   [0m src.libs.common:common.py:30 Attaching file ./log/docker/receiving_node1_2024-05-24_10-01-39__7cdfc000-5693-4254-96b1-accc9b124ac6__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.libs.common:common.py:30 Attaching file ./log/docker/lightpush_node1_2024-05-24_10-01-39__7cdfc000-5693-4254-96b1-accc9b124ac6__harbor.status.im_wakuorg_nwaku:latest.log