[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_filter_subscribe_with_invalid_request_id with id: 2024-02-27_04-13-18__187bb79f-bfff-42ed-b3fb-25548d71b4e5
[35mDEBUG   [0m src.steps.filter:filter.py:27 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:33 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node1_2024-02-27_04-13-18__187bb79f-bfff-42ed-b3fb-25548d71b4e5__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:78 Generated random external IP 172.18.210.218
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:71 Generated ports ['64563', '64564', '64565', '64566', '64567']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:276 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:45 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:46 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=64565', '--rest-port=64563', '--tcp-port=64564', '--discv5-udp-port=64566', '--rest-address=0.0.0.0', '--nat=extip:172.18.210.218', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=64567', '--metrics-logging=true', '--relay=true', '--filter=true', '--nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 Container started with ID be65082ca51b. Setting up logs at ./log/docker/node1_2024-02-27_04-13-18__187bb79f-bfff-42ed-b3fb-25548d71b4e5__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 64563
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:64563/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.210.218/tcp/64564/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.210.218/tcp/64565/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-Kq4QJOWgjnXBH0SR2Tsl95OaFe_i5edgQpSm8BUhDDxZNBXRi_M2hvwudGYMZu9UXMnKPlZwUstSGFmLNlgTIQvHtMBgmlkgnY0gmlwhKwS0tqKbXVsdGlhZGRyc4wACgSsEtLaBvw13QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC_DSDdWRwgvw2hXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:38 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:50 WakuNode instance initialized with log path ./log/docker/node2_2024-02-27_04-13-18__187bb79f-bfff-42ed-b3fb-25548d71b4e5__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:54 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:78 Generated random external IP 172.18.186.165
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:71 Generated ports ['4464', '4465', '4466', '4467', '4468']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:276 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:115 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:45 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:46 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=4466', '--rest-port=4464', '--tcp-port=4465', '--discv5-udp-port=4467', '--rest-address=0.0.0.0', '--nat=extip:172.18.186.165', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=4468', '--metrics-logging=true', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QJOWgjnXBH0SR2Tsl95OaFe_i5edgQpSm8BUhDDxZNBXRi_M2hvwudGYMZu9UXMnKPlZwUstSGFmLNlgTIQvHtMBgmlkgnY0gmlwhKwS0tqKbXVsdGlhZGRyc4wACgSsEtLaBvw13QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC_DSDdWRwgvw2hXdha3UyBQ', '--filternode=/ip4/172.18.210.218/tcp/64564/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:54 Container started with ID 8ddee24c9bd6. Setting up logs at ./log/docker/node2_2024-02-27_04-13-18__187bb79f-bfff-42ed-b3fb-25548d71b4e5__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:121 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 4464
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:4464/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.186.165/tcp/4465/p2p/16Uiu2HAmQfQ2QFPG84JerU2x5ThShkdtrJ6S3DTa79ofeJ2yKCJa","/ip4/172.18.186.165/tcp/4466/ws/p2p/16Uiu2HAmQfQ2QFPG84JerU2x5ThShkdtrJ6S3DTa79ofeJ2yKCJa"],"enrUri":"enr:-Kq4QOLgELXWg1iBbFlqJaFqu136xgZdMFSKefCtYvFTiVeiX5opt-_6LiHKhM6lSdKGYFxs1ONO6xyNjjaQiS5nbugBgmlkgnY0gmlwhKwSuqWKbXVsdGlhZGRyc4wACgSsErqlBhFy3QOJc2VjcDI1NmsxoQOyZwMD7nbhNT-LGGgbEwib4d7Qr6lQaT1RjnmGdnCdN4N0Y3CCEXGDdWRwghFzhXdha3UyBA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:191 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:45 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 POST call: http://127.0.0.1:64563/relay/v1/subscriptions with payload: ["/waku/2/rs/0/1"]
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 POST call: http://127.0.0.1:4464/filter/v2/subscriptions with payload: {"requestId": "12370cfb-ab54-4654-978d-82e1668cc4b9", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"12370cfb-ab54-4654-978d-82e1668cc4b9","statusCode":0,"statusDesc":""}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 POST call: http://127.0.0.1:4464/filter/v2/subscriptions with payload: {"requestId": 1, "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:4464/filter/v2/subscriptions. Response content: b'{"requestId":"unknown","statusCode":400,"statusDesc":"BAD_REQUEST: Failed to decode request: (status: 400 Bad Request, headers: , kind: Error, errobj: (status: 400 Bad Request, message: \\"Invalid content body, could not decode. Unable to deserialize data\\", contentType: \\"text/plain\\"))"}'
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id be65082ca51b
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:168 Stopping container with id 8ddee24c9bd6
[35mDEBUG   [0m src.node.waku_node:waku_node.py:171 Container stopped.