[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_ping_on_peer_without_subscription with id: 2024-06-16_03-11-49__5bc8fc4a-6a9d-4dec-9af6-897d307b0d10
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/node1_2024-06-16_03-11-49__5bc8fc4a-6a9d-4dec-9af6-897d307b0d10__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.21.156
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['49893', '49894', '49895', '49896', '49897']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:373 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:120 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 49893:49893 -p 49894:49894 -p 49895:49895 -p 49896:49896 -p 49897:49897 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=49895 --rest-port=49893 --tcp-port=49894 --discv5-udp-port=49896 --rest-address=0.0.0.0 --nat=extip:172.18.21.156 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=49897 --metrics-logging=true --relay=true --filter=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.21.156 waku 325f69ff7b29b25ea52b02815980d3cddd7bf527685ae6c4c97b7cf6e38f42af
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 325f69ff7b29. Setting up logs at ./log/docker/node1_2024-06-16_03-11-49__5bc8fc4a-6a9d-4dec-9af6-897d307b0d10__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:134 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 49893
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:49893/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:225 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:49893/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.21.156/tcp/49895/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QLxBfVLmN3RxTDwjxFuMh1_o1jwAJgbp6vUcEK9SGG75SnhRyXsvcpaboXUzpDPEs8sF8qMtICa9CxN4eIxUOOkBgmlkgnY0gmlwhKwSFZyKbXVsdGlhZGRyc4wACgSsEhWcBsLn3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCwuaDdWRwgsLohXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:230 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/node2_2024-06-16_03-11-49__5bc8fc4a-6a9d-4dec-9af6-897d307b0d10__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.200.93
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['3350', '3351', '3352', '3353', '3354']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:373 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:120 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 3350:3350 -p 3351:3351 -p 3352:3352 -p 3353:3353 -p 3354:3354 harbor.status.im/wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=3352 --rest-port=3350 --tcp-port=3351 --discv5-udp-port=3353 --rest-address=0.0.0.0 --nat=extip:172.18.200.93 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --relay=false --discv5-bootstrap-node=enr:-LO4QLxBfVLmN3RxTDwjxFuMh1_o1jwAJgbp6vUcEK9SGG75SnhRyXsvcpaboXUzpDPEs8sF8qMtICa9CxN4eIxUOOkBgmlkgnY0gmlwhKwSFZyKbXVsdGlhZGRyc4wACgSsEhWcBsLn3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCwuaDdWRwgsLohXdha3UyBQ --filternode=/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.200.93 waku c26e4cee4ae036ede6afd6790e37c08dda41c9e5aea0e19d266a70a8fc32fd12
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID c26e4cee4ae0. Setting up logs at ./log/docker/node2_2024-06-16_03-11-49__5bc8fc4a-6a9d-4dec-9af6-897d307b0d10__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:134 Started container from image harbor.status.im/wakuorg/go-waku:latest. REST: 3350
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:3350/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ly4QJ9LQWaltzUJCNbGkHEZF7XGhdGl86TbQ-4GC_KBII4gGvvx8Jq45aMfgmYCCTxFcVf7fofr4NZcLSYY-R-soFKGAZAfB59cgmlkgnY0gmlwhKwRAAeKbXVsdGlhZGRyc5gACgSsEQAHBg0Y3QMACgR_AAABBg0Y3QOJc2VjcDI1NmsxoQIUlyXf5mUe4sLTIX74CjKd1Bjotgs0vkEyMuctu9UI6oN0Y3CCDReDdWRwgg0ZhXdha3UygA","listenAddresses":["/ip4/127.0.0.1/tcp/3351/p2p/16Uiu2HAkvp3ovz3kC8d4A5Wjdv73u8RiyH3KRMwMiFwQiG2d28am","/ip4/127.0.0.1/tcp/3352/ws/p2p/16Uiu2HAkvp3ovz3kC8d4A5Wjdv73u8RiyH3KRMwMiFwQiG2d28am","/ip4/172.17.0.7/tcp/3351/p2p/16Uiu2HAkvp3ovz3kC8d4A5Wjdv73u8RiyH3KRMwMiFwQiG2d28am","/ip4/172.17.0.7/tcp/3352/ws/p2p/16Uiu2HAkvp3ovz3kC8d4A5Wjdv73u8RiyH3KRMwMiFwQiG2d28am"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:230 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:3350/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:3350/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:3350/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:3350/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:3350/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:3350/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:3350/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:3350/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:3350/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:3350/admin/v1/peers. Response content: b''
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:3350/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.21.156/tcp/49894/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:3350/filter/v2/subscriptions/7f3a8c19-c96b-4624-b32d-41fcca3f191f" -H "Content-Type: application/json" -d 'None'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 404 Client Error: Not Found for url: http://127.0.0.1:3350/filter/v2/subscriptions/7f3a8c19-c96b-4624-b32d-41fcca3f191f. Response content: b'{"requestId":"7f3a8c19-c96b-4624-b32d-41fcca3f191f","statusDesc":"peer has no subscription"}'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:181 Stopping container with id 325f69ff7b29
[35mDEBUG   [0m src.node.waku_node:waku_node.py:188 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:181 Stopping container with id c26e4cee4ae0
[35mDEBUG   [0m src.node.waku_node:waku_node.py:188 Container stopped.