[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_subscribe_with_no_content_topic with id: 2025-01-17_04-02-38__b22b9c99-64ac-4b12-ab14-d93b967ff768
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2025-01-17_04-02-38__b22b9c99-64ac-4b12-ab14-d93b967ff768__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.17.104
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['56358', '56359', '56360', '56361', '56362']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 56358:56358 -p 56359:56359 -p 56360:56360 -p 56361:56361 -p 56362:56362 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=56360 --rest-port=56358 --tcp-port=56359 --discv5-udp-port=56361 --rest-address=0.0.0.0 --nat=extip:172.18.17.104 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=01ddb224f1b1ae903498ed67b3f3d00c8cf1546fb03ede4452aa2a68bb7a4a4e --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=56362 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.17.104 waku f394218139b2ea2887d2493b1bc772c0bc2f5dd65b873acdc63ae7b402f5a70b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID f394218139b2. Setting up logs at ./log/docker/node1_2025-01-17_04-02-38__b22b9c99-64ac-4b12-ab14-d93b967ff768__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 56358
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container e66d4db49d0c. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:56358/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:56358/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.17.104/tcp/56359/p2p/16Uiu2HAmLDXy8oXegZNwpCdRWUaX8vqdT6VWNYCNEQFzedfyRQ7C","/ip4/172.18.17.104/tcp/56360/ws/p2p/16Uiu2HAmLDXy8oXegZNwpCdRWUaX8vqdT6VWNYCNEQFzedfyRQ7C"],"enrUri":"enr:-L24QPJYcBMU96EMQz5HzE6lnguI9RjDVUV2vKe4iwAGIn3ERLy80DsKHorlZTbrnrKNYm5tQ7DttlQETD07CJzWrKECgmlkgnY0gmlwhKwSEWiKbXVsdGlhZGRyc5YACASsEhFoBtwnAAoErBIRaAbcKN0DgnJzhQADAQAAiXNlY3AyNTZrMaEDcFglHg9h5wmD9OtUajymVCnAFfoxWOaNMJtJnSi9MyODdGNwgtwng3VkcILcKYV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2025-01-17_04-02-38__b22b9c99-64ac-4b12-ab14-d93b967ff768__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.211.190
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['25817', '25818', '25819', '25820', '25821']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 25817:25817 -p 25818:25818 -p 25819:25819 -p 25820:25820 -p 25821:25821 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=25819 --rest-port=25817 --tcp-port=25818 --discv5-udp-port=25820 --rest-address=0.0.0.0 --nat=extip:172.18.211.190 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=f6c0ca54d348b2eedc3ccddcacadecfcafb7506c5e2a4eedffa8ee23ce0cf8ef --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=25821 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QPJYcBMU96EMQz5HzE6lnguI9RjDVUV2vKe4iwAGIn3ERLy80DsKHorlZTbrnrKNYm5tQ7DttlQETD07CJzWrKECgmlkgnY0gmlwhKwSEWiKbXVsdGlhZGRyc5YACASsEhFoBtwnAAoErBIRaAbcKN0DgnJzhQADAQAAiXNlY3AyNTZrMaEDcFglHg9h5wmD9OtUajymVCnAFfoxWOaNMJtJnSi9MyODdGNwgtwng3VkcILcKYV3YWt1MgU --filternode=/ip4/172.18.17.104/tcp/56359/p2p/16Uiu2HAmLDXy8oXegZNwpCdRWUaX8vqdT6VWNYCNEQFzedfyRQ7C
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.211.190 waku b6e5ba6f4fa3b4f47d626d6dec4cc64e66551fda10fa2ebb2880991280c45559
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID b6e5ba6f4fa3. Setting up logs at ./log/docker/node2_2025-01-17_04-02-38__b22b9c99-64ac-4b12-ab14-d93b967ff768__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 25817
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:25817/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:25817/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.211.190/tcp/25818/p2p/16Uiu2HAkwjv8GhmfP4fZZnXs2fgqsYkbtDBMH7UMcpW2aCQN79JP","/ip4/172.18.211.190/tcp/25819/ws/p2p/16Uiu2HAkwjv8GhmfP4fZZnXs2fgqsYkbtDBMH7UMcpW2aCQN79JP"],"enrUri":"enr:-L24QG0KP3aRrpNJljOfPpfN4ZuhosXCbeEh06aZFFADBJ7_LPI5N9J9YbXf1OaR7xY4Zz936oT10VqVOFTaek0yThMCgmlkgnY0gmlwhKwS076KbXVsdGlhZGRyc5YACASsEtO-BmTaAAoErBLTvgZk290DgnJzhQADAQAAiXNlY3AyNTZrMaECImPS09fSiBytMtaVxw7OEU_BlGGuIQodWvSPjn6Ak_CDdGNwgmTag3VkcIJk3IV3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:25817/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.17.104/tcp/56359/p2p/16Uiu2HAmLDXy8oXegZNwpCdRWUaX8vqdT6VWNYCNEQFzedfyRQ7C"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:56358/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:25817/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "19b43df3-5661-45d8-8e14-17c45d9aba2f", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"19b43df3-5661-45d8-8e14-17c45d9aba2f","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:25817/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "1", "pubsubTopic": "/waku/2/rs/3/1"}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:25817/filter/v2/subscriptions. Response content: b'{"requestId":"unknown","statusDesc":"BAD_REQUEST: Failed to decode request: (status: 400 Bad Request, headers: , kind: Error, errobj: (status: 400 Bad Request, message: \\"Invalid content body, could not decode. Unable to deserialize data\\", contentType: \\"text/plain\\"))"}'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id f394218139b2
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id b6e5ba6f4fa3
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container f394218139b2. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.