[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_ping_only_some_nodes_have_subscriptions with id: 2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f
[35mDEBUG   [0m src.steps.filter:filter.py:27 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:33 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:21 WakuNode instance initialized with log path ./log/docker/node1_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:25 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated random external IP 172.18.238.6
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:66 Generated ports ['30059', '30060', '30061', '30062', '30063']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:42 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:43 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=30061', '--rest-port=30059', '--tcp-port=30060', '--discv5-udp-port=30062', '--rest-address=0.0.0.0', '--nat=extip:172.18.238.6', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=30063', '--metrics-logging=true', '--relay=true', '--filter=true', '--nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 Container started with ID 78fd4d3f5216. Setting up logs at ./log/docker/node1_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:78 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 30059
[35mDEBUG   [0m src.libs.common:common.py:33 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:30059/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.238.6/tcp/30060/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.238.6/tcp/30061/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-Kq4QNsh3FT6PRjTa6BHqO8WQQ4J4tKuctdEngt0d_YyVjuwC50fpXam48Obh7uzeprfhJM-yzudl4jl3W9O853OuhwBgmlkgnY0gmlwhKwS7gaKbXVsdGlhZGRyc4wACgSsEu4GBnVt3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCdWyDdWRwgnVuhXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:113 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:38 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:21 WakuNode instance initialized with log path ./log/docker/node2_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:25 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated random external IP 172.18.41.106
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:66 Generated ports ['32145', '32146', '32147', '32148', '32149']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:42 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:43 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=32147', '--rest-port=32145', '--tcp-port=32146', '--discv5-udp-port=32148', '--rest-address=0.0.0.0', '--nat=extip:172.18.41.106', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=32149', '--metrics-logging=true', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QNsh3FT6PRjTa6BHqO8WQQ4J4tKuctdEngt0d_YyVjuwC50fpXam48Obh7uzeprfhJM-yzudl4jl3W9O853OuhwBgmlkgnY0gmlwhKwS7gaKbXVsdGlhZGRyc4wACgSsEu4GBnVt3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCdWyDdWRwgnVuhXdha3UyBQ', '--filternode=/ip4/172.18.238.6/tcp/30060/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 Container started with ID 9f861ca25a28. Setting up logs at ./log/docker/node2_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:78 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 32145
[35mDEBUG   [0m src.libs.common:common.py:33 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:32145/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.41.106/tcp/32146/p2p/16Uiu2HAkuyoZQ6n8KHxbk3ubNqMgNNF3RdDGzYGp8Leg9qzvKgJr","/ip4/172.18.41.106/tcp/32147/ws/p2p/16Uiu2HAkuyoZQ6n8KHxbk3ubNqMgNNF3RdDGzYGp8Leg9qzvKgJr"],"enrUri":"enr:-Kq4QGjXAF4Fjx_1tSm9osPqZW9k0SgDKkb5VPjazFeY5mPTPUtmrUrNLcRVCFuLWEnH8fv8ekUj47-_Ryu2qoxVZ8EBgmlkgnY0gmlwhKwSKWqKbXVsdGlhZGRyc4wACgSsEilqBn2T3QOJc2VjcDI1NmsxoQIIOyfsgKBs-G4ITuv-VYOAsd4aTHSKOiLLnBwaLrndR4N0Y3CCfZKDdWRwgn2UhXdha3UyBA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:113 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 POST call: http://127.0.0.1:30059/relay/v1/subscriptions with payload: ["/waku/2/rs/0/1"]
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 POST call: http://127.0.0.1:32145/filter/v2/subscriptions with payload: {"requestId": "ad4c5a44-8bf5-491a-8e76-9acec5220f56", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/0/1"}
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"ad4c5a44-8bf5-491a-8e76-9acec5220f56","statusCode":0,"statusDesc":""}'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:21 WakuNode instance initialized with log path ./log/docker/additional_node1_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:25 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated random external IP 172.18.99.192
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:66 Generated ports ['38272', '38273', '38274', '38275', '38276']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:42 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:43 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=38274', '--rest-port=38272', '--tcp-port=38273', '--discv5-udp-port=38275', '--rest-address=0.0.0.0', '--nat=extip:172.18.99.192', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=38276', '--metrics-logging=true', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QNsh3FT6PRjTa6BHqO8WQQ4J4tKuctdEngt0d_YyVjuwC50fpXam48Obh7uzeprfhJM-yzudl4jl3W9O853OuhwBgmlkgnY0gmlwhKwS7gaKbXVsdGlhZGRyc4wACgSsEu4GBnVt3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCdWyDdWRwgnVuhXdha3UyBQ', '--filternode=/ip4/172.18.238.6/tcp/30060/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 Container started with ID efc4563c32d0. Setting up logs at ./log/docker/additional_node1_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:78 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 38272
[35mDEBUG   [0m src.libs.common:common.py:33 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:38272/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.99.192/tcp/38273/p2p/16Uiu2HAkzsvRGXFPTr62u66YKovYMgjk42uPYEM9KmHx1VBc3eoA","/ip4/172.18.99.192/tcp/38274/ws/p2p/16Uiu2HAkzsvRGXFPTr62u66YKovYMgjk42uPYEM9KmHx1VBc3eoA"],"enrUri":"enr:-Kq4QJ_0uJkR2FuTbdg74sIWp89CVk5-l1WQnJyKCTc55VOBRwVKTz0O8r605l1Bg6-m5ZeiefRI7QKNhpKcwbJD-7IBgmlkgnY0gmlwhKwSY8CKbXVsdGlhZGRyc4wACgSsEmPABpWC3QOJc2VjcDI1NmsxoQJRA9y1yDkvmBH70qgseUwm_j6_I9vmCW6sC4G5P77MaYN0Y3CClYGDdWRwgpWDhXdha3UyBA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:113 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:21 WakuNode instance initialized with log path ./log/docker/additional_node2_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:25 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated random external IP 172.18.210.81
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:66 Generated ports ['23467', '23468', '23469', '23470', '23471']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:42 Starting container with image harbor.status.im/wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:43 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=DEBUG', '--rest-relay-cache-capacity=100', '--websocket-port=23469', '--rest-port=23467', '--tcp-port=23468', '--discv5-udp-port=23470', '--rest-address=0.0.0.0', '--nat=extip:172.18.210.81', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--min-relay-peers-to-publish=1', '--legacy-filter=false', '--rest-filter-cache-capacity=50', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QNsh3FT6PRjTa6BHqO8WQQ4J4tKuctdEngt0d_YyVjuwC50fpXam48Obh7uzeprfhJM-yzudl4jl3W9O853OuhwBgmlkgnY0gmlwhKwS7gaKbXVsdGlhZGRyc4wACgSsEu4GBnVt3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCdWyDdWRwgnVuhXdha3UyBQ', '--filternode=/ip4/172.18.238.6/tcp/30060/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 Container started with ID eda227ac0da9. Setting up logs at ./log/docker/additional_node2_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:78 Started container from image harbor.status.im/wakuorg/go-waku:latest. REST: 23467
[35mDEBUG   [0m src.libs.common:common.py:33 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:23467/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ly4QJId5L24BvXmA3kboaBZuWTvp7wqYKJOK3BHY84X0XUaECL4laK7jTo_XCkcfcJCqbVcHZV-WgkqcYeg4RZ9tvuGAY1YkfIOgmlkgnY0gmlwhKwRAAmKbXVsdGlhZGRyc5gACgR_AAABBlut3QMACgSsEQAJBlut3QOJc2VjcDI1NmsxoQKIjIcyjsEQYnbwuesjBzzhBC3HwmtZTm0CZTlCCfFUOoN0Y3CCW6yDdWRwgluuhXdha3UyBA","listenAddresses":["/ip4/127.0.0.1/tcp/23468/p2p/16Uiu2HAm4chiAxiWDR6sQYTwHTdopCbxqQ2GzSY6FVuZbhWcXjdj","/ip4/127.0.0.1/tcp/23469/ws/p2p/16Uiu2HAm4chiAxiWDR6sQYTwHTdopCbxqQ2GzSY6FVuZbhWcXjdj","/ip4/172.17.0.9/tcp/23468/p2p/16Uiu2HAm4chiAxiWDR6sQYTwHTdopCbxqQ2GzSY6FVuZbhWcXjdj","/ip4/172.17.0.9/tcp/23469/ws/p2p/16Uiu2HAm4chiAxiWDR6sQYTwHTdopCbxqQ2GzSY6FVuZbhWcXjdj"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:113 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:21 WakuNode instance initialized with log path ./log/docker/additional_node3_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:25 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated random external IP 172.18.129.255
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:66 Generated ports ['46172', '46173', '46174', '46175', '46176']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:42 Starting container with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:43 Using args ['--listen-address=0.0.0.0', '--rest=true', '--rest-admin=true', '--websocket-support=true', '--log-level=TRACE', '--rest-relay-cache-capacity=100', '--websocket-port=46174', '--rest-port=46172', '--tcp-port=46173', '--discv5-udp-port=46175', '--rest-address=0.0.0.0', '--nat=extip:172.18.129.255', '--peer-exchange=true', '--discv5-discovery=true', '--cluster-id=0', '--metrics-server=true', '--metrics-server-address=0.0.0.0', '--metrics-server-port=46176', '--metrics-logging=true', '--relay=false', '--filter=true', '--discv5-bootstrap-node=enr:-Kq4QNsh3FT6PRjTa6BHqO8WQQ4J4tKuctdEngt0d_YyVjuwC50fpXam48Obh7uzeprfhJM-yzudl4jl3W9O853OuhwBgmlkgnY0gmlwhKwS7gaKbXVsdGlhZGRyc4wACgSsEu4GBnVt3QOJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCdWyDdWRwgnVuhXdha3UyBQ', '--filternode=/ip4/172.18.238.6/tcp/30060/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 Container started with ID 7b24dd505147. Setting up logs at ./log/docker/additional_node3_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:78 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 46172
[35mDEBUG   [0m src.libs.common:common.py:33 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:46172/debug/v1/info with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.129.255/tcp/46173/p2p/16Uiu2HAm6bykx6Krb4FYCroCz1DXdQThCxWmS1PgVefDMctakUWy","/ip4/172.18.129.255/tcp/46174/ws/p2p/16Uiu2HAm6bykx6Krb4FYCroCz1DXdQThCxWmS1PgVefDMctakUWy"],"enrUri":"enr:-Kq4QJyjBPbHK4YLLbS8Skcz9vaIk4cIOB7NYJffcFR08hjSKZqQ6iqRWrgTatdoecDxpswtbFD2IJqOZnI9kmvw2RABgmlkgnY0gmlwhKwSgf-KbXVsdGlhZGRyc4wACgSsEoH_BrRe3QOJc2VjcDI1NmsxoQKmFHdxgcC9nDTNy3dMQmJyw3ZaLrfX7JVRtJemy8xk_oN0Y3CCtF2DdWRwgrRfhXdha3UyBA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:113 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:32145/filter/v2/subscriptions/1 with payload: None
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"1","statusCode":0,"statusDesc":""}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:38272/filter/v2/subscriptions/74ea2f9f-fd31-4cea-b7dc-8f86acaf4bd2 with payload: None
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 404 Client Error: Not Found for url: http://127.0.0.1:38272/filter/v2/subscriptions/74ea2f9f-fd31-4cea-b7dc-8f86acaf4bd2. Response content: b'{"requestId":"74ea2f9f-fd31-4cea-b7dc-8f86acaf4bd2","statusCode":404,"statusDesc":"NOT_FOUND: peer has no subscriptions"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:11 GET call: http://127.0.0.1:23467/filter/v2/subscriptions/7d17bc79-bef9-4ca1-af86-1b57fe01e1bc with payload: None
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 500 Server Error: Internal Server Error for url: http://127.0.0.1:23467/filter/v2/subscriptions/7d17bc79-bef9-4ca1-af86-1b57fe01e1bc. Response content: b'{"requestId":"7d17bc79-bef9-4ca1-af86-1b57fe01e1bc","statusDesc":"ping request failed"}'
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:90 Stopping container with id 78fd4d3f5216
[35mDEBUG   [0m src.node.waku_node:waku_node.py:93 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:90 Stopping container with id 9f861ca25a28
[35mDEBUG   [0m src.node.waku_node:waku_node.py:93 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:90 Stopping container with id efc4563c32d0
[35mDEBUG   [0m src.node.waku_node:waku_node.py:93 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:90 Stopping container with id eda227ac0da9
[35mDEBUG   [0m src.node.waku_node:waku_node.py:93 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:90 Stopping container with id 7b24dd505147
[35mDEBUG   [0m src.node.waku_node:waku_node.py:93 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:65 Running fixture teardown: attach_logs_on_fail
[35mDEBUG   [0m tests.conftest:conftest.py:66 Test failed, attempting to attach logs to the allure reports
[35mDEBUG   [0m src.libs.common:common.py:28 Attaching file ./log/docker/additional_node3_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.libs.common:common.py:28 Attaching file ./log/docker/node1_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.libs.common:common.py:28 Attaching file ./log/docker/additional_node1_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.libs.common:common.py:28 Attaching file ./log/docker/additional_node2_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.libs.common:common.py:28 Attaching file ./log/docker/node2_2024-01-30_04-12-49__b1f2d3ce-d2d3-463e-9f5c-bc13d9c27f0f__harbor.status.im_wakuorg_nwaku:latest.log